# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snapkittest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  

  # Pods for snapkittest
 

end

target 'sios10' do
  platform :ios, '10.0'
  use_frameworks!
  pod 'SnapSDK'
end
